<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>schemetests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="core\**" />
    <EmbeddedResource Include="tests\**" />
    <EmbeddedResource Include="failures\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\scheme\scheme.csproj" />
  </ItemGroup>
</Project>
