package scheme;

import java.io.File;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PushbackReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import scheme.primitives.*;

public class Primitives {
    private HashMap<String, Object> primitives = new HashMap<>();

    public Primitives() {
    }

    public void init(Modules modules) {
        bind("*error-port*", new OutputStreamWriter(System.err));
        bind("*input-port*", new TextStream(new PushbackReader(new InputStreamReader(System.in)), "{stdin}"));
        bind("*output-port*", new OutputStreamWriter(System.out));
        bind("E", Math.E);
        bind("PI", Math.PI);
        bind("apply", getApply());
        bind("call-with-current-continuation", getCallCC());
        bind("call-with-values", getCallWithValues());
        bind("field-sep", System.getProperty("path.separator").toCharArray());
        bind("line-sep", System.getProperty("line.separator").toCharArray());
        bind("nil", Value.NIL);
        bind("path-sep", new char[] { File.separatorChar });
        bind(new PrimitiveAbandonedMutexExceptionP());
        bind(new PrimitiveAbsolutePath());
        bind(new PrimitiveAcos());
        bind(new PrimitiveAdd());
        bind(new PrimitiveAesCbcDecrypt());
        bind(new PrimitiveAesCbcEncrypt());
        bind(new PrimitiveAesEcbDecrypt());
        bind(new PrimitiveAesEcbEncrypt());
        bind(new PrimitiveAesGcmDecrypt());
        bind(new PrimitiveAesGcmEncrypt());
        bind(new PrimitiveAppend());
        bind(new PrimitiveArithmeticShift());
        bind(new PrimitiveAsin());
        bind(new PrimitiveAtan());
        bind(new PrimitiveBase64Decode());
        bind(new PrimitiveBase64Encode());
        bind(new PrimitiveBaseName());
        bind(new PrimitiveBinaryPortP());
        bind(new PrimitiveBitCount());
        bind(new PrimitiveBitwiseAnd());
        bind(new PrimitiveBitwiseIor());
        bind(new PrimitiveBitwiseNot());
        bind(new PrimitiveBitwiseXor());
        bind(new PrimitiveBooleanP());
        bind(new PrimitiveBoundIdentifierEqP());
        bind(new PrimitiveBoundP(modules));
        bind(new PrimitiveBytevector());
        bind(new PrimitiveBytevectorAppend());
        bind(new PrimitiveBytevectorCopy());
        bind(new PrimitiveBytevectorCopyB());
        bind(new PrimitiveBytevectorLength());
        bind(new PrimitiveBytevectorP());
        bind(new PrimitiveBytevectorU8Ref());
        bind(new PrimitiveBytevectorU8SetB());
        bind(new PrimitiveCaar());
        bind(new PrimitiveCadar());
        bind(new PrimitiveCadr());
        bind(new PrimitiveCar());
        bind(new PrimitiveCdr());
        bind(new PrimitiveCeiling());
        bind(new PrimitiveChaCha20Poly1305Decrypt());
        bind(new PrimitiveChaCha20Poly1305Encrypt());
        bind(new PrimitiveCharAlphabeticP());
        bind(new PrimitiveCharDowncase());
        bind(new PrimitiveCharEqP());
        bind(new PrimitiveCharFoldcase());
        bind(new PrimitiveCharGreaterEqP());
        bind(new PrimitiveCharGreaterP());
        bind(new PrimitiveCharLessEqP());
        bind(new PrimitiveCharLessP());
        bind(new PrimitiveCharLowerCaseP());
        bind(new PrimitiveCharNumericP());
        bind(new PrimitiveCharP());
        bind(new PrimitiveCharToInteger());
        bind(new PrimitiveCharUpcase());
        bind(new PrimitiveCharUpperCaseP());
        bind(new PrimitiveCharWhitespaceP());
        bind(new PrimitiveCloseInputPort());
        bind(new PrimitiveCloseInputZip());
        bind(new PrimitiveCloseJson());
        bind(new PrimitiveCloseOutputPort());
        bind(new PrimitiveCloseOutputZip());
        bind(new PrimitiveCloseRandomAccessFile());
        bind(new PrimitiveCloseXml());
        bind(new PrimitiveCommandLine());
        bind(new PrimitiveCompile(modules));
        bind(new PrimitiveComplexAngle());
        bind(new PrimitiveComplexImagPart());
        bind(new PrimitiveComplexMagnitude());
        bind(new PrimitiveComplexP());
        bind(new PrimitiveComplexRealPart());
        bind(new PrimitiveConditionVariableBroadcastB());
        bind(new PrimitiveConditionVariableName());
        bind(new PrimitiveConditionVariableP());
        bind(new PrimitiveConditionVariableSignalB());
        bind(new PrimitiveConditionVariableSpecific());
        bind(new PrimitiveConditionVariableSpecificSetB());
        bind(new PrimitiveConsoleEchoB());
        bind(new PrimitiveConsoleReadPassword());
        bind(new PrimitiveCons());
        bind(new PrimitiveCopyDirectory());
        bind(new PrimitiveCopyFile());
        bind(new PrimitiveCos());
        bind(new PrimitiveCrc32());
        bind(new PrimitiveCreateModule(modules));
        bind(new PrimitiveCsvLineToFields());
        bind(new PrimitiveCurrentDirectory());
        bind(new PrimitiveCurrentModule(modules));
        bind(new PrimitiveCurrentModuleName(modules));
        bind(new PrimitiveCurrentNanosecond());
        bind(new PrimitiveCurrentPid());
        bind(new PrimitiveCurrentSourceLocation());
        bind(new PrimitiveCurrentThread());
        bind(new PrimitiveDatumToSyntax());
        bind(new PrimitiveDeflateCompress());
        bind(new PrimitiveDeflateDecompress());
        bind(new PrimitiveDeleteDirectory());
        bind(new PrimitiveDeleteFile());
        bind(new PrimitiveDictClear());
        bind(new PrimitiveDictContains());
        bind(new PrimitiveDictEntries());
        bind(new PrimitiveDictGet());
        bind(new PrimitiveDictKeys());
        bind(new PrimitiveDictPut());
        bind(new PrimitiveDictSize());
        bind(new PrimitiveDictValues());
        bind(new PrimitiveDigitValue());
        bind(new PrimitiveDirectoryDirectories());
        bind(new PrimitiveDirectoryEntries());
        bind(new PrimitiveDirectoryExists());
        bind(new PrimitiveDirectoryFiles());
        bind(new PrimitiveDirectoryName());
        bind(new PrimitiveDisassemble(modules));
        bind(new PrimitiveDisplay(modules));
        bind(new PrimitiveDiv());
        bind(new PrimitiveDoImportSet(modules));
        bind(new PrimitiveDoc(modules));
        bind(new PrimitiveEOFObjectP());
        bind(new PrimitiveEnvironment(modules));
        bind(new PrimitiveEqP());
        bind(new PrimitiveEqualP());
        bind(new PrimitiveEqvP());
        bind(new PrimitiveError());
        bind(new PrimitiveErrorObjectIrritants());
        bind(new PrimitiveErrorObjectMessage());
        bind(new PrimitiveErrorObjectP());
        bind(new PrimitiveEval(modules));
        bind(new PrimitiveExact());
        bind(new PrimitiveExactP());
        bind(new PrimitiveExceptionHandlersGet());
        bind(new PrimitiveExceptionHandlersSet());
        bind(new PrimitiveExit(modules));
        bind(new PrimitiveSetExitCode());
        bind(new PrimitiveExpt());
        bind(new PrimitiveFeaturesList());
        bind(new PrimitiveFileErrorP());
        bind(new PrimitiveFileExists());
        bind(new PrimitiveFileModificationDate());
        bind(new PrimitiveFileModificationTimestamp());
        bind(new PrimitiveFileLock());
        bind(new PrimitiveFileSize());
        bind(new PrimitiveFileSymlinkP());
        bind(new PrimitiveFileUnlock());
        bind(new PrimitiveFirst());
        bind(new PrimitiveFloor());
        bind(new PrimitiveFlushOutputPort(modules));
        bind(new PrimitiveFormat(modules));
        bind(new PrimitiveFreeIdentifierEqP(modules));
        bind(new PrimitiveGenerateTemporaries());
        bind(new PrimitiveGensym());
        bind(new PrimitiveGetBytes());
        bind(new PrimitiveGetCode());
        bind(new PrimitiveGetEnvironmentVariable());
        bind(new PrimitiveGetEnvironmentVariables());
        bind(new PrimitiveGetLambdaEnv());
        bind(new PrimitiveGetOutputBytevector());
        bind(new PrimitiveGetOutputString());
        bind(new PrimitiveGetOutputZipBytevector());
        bind(new PrimitiveGetProperty());
        bind(new PrimitiveGetPropertyList());
        bind(new PrimitiveGetToken(modules));
        bind(new PrimitiveGzipCompress());
        bind(new PrimitiveGzipDecompress());
        bind(new PrimitiveHMACSHA256());
        bind(new PrimitiveHashTableClearB());
        bind(new PrimitiveHashTableComparator());
        bind(new PrimitiveHashTableCopy());
        bind(new PrimitiveHashTableDeleteB());
        bind(new PrimitiveHashTableExistsP());
        bind(new PrimitiveHashTableKeys());
        bind(new PrimitiveHashTableP());
        bind(new PrimitiveHashTableRef());
        bind(new PrimitiveHashTableRefDefault());
        bind(new PrimitiveHashTableSetB());
        bind(new PrimitiveHashTableSetComparatorB());
        bind(new PrimitiveHashTableSize());
        bind(new PrimitiveHashTableToAlist());
        bind(new PrimitiveHashTableValues());
        bind(new PrimitiveHtmlEscape());
        bind(new PrimitiveHttpGet());
        bind(new PrimitiveHttpPost());
        bind(new PrimitiveHttpRequestBody());
        bind(new PrimitiveHttpRequestBodyBytes());
        bind(new PrimitiveHttpRequestHeaders());
        bind(new PrimitiveHttpRequestMethod());
        bind(new PrimitiveHttpRequestP());
        bind(new PrimitiveHttpRequestUrl());
        bind(new PrimitiveHttpResponseBody());
        bind(new PrimitiveHttpResponseHeaders());
        bind(new PrimitiveHttpResponseP());
        bind(new PrimitiveHttpResponseStatus());
        bind(new PrimitiveHttpSend());
        bind(new PrimitiveIdentifierP());
        bind(new PrimitiveInclude(modules));
        bind(new PrimitiveIncludeCi(modules));
        bind(new PrimitiveInexact());
        bind(new PrimitiveInputPortOpenP());
        bind(new PrimitiveInputPortP());
        bind(new PrimitiveInstructionArg1());
        bind(new PrimitiveInstructionArg2());
        bind(new PrimitiveInstructionOpcode());
        bind(new PrimitiveIntegerLength());
        bind(new PrimitiveIntegerP());
        bind(new PrimitiveIntegerToChar());
        bind(new PrimitiveJiffy());
        bind(new PrimitiveJoinTimeoutExceptionP());
        bind(new PrimitiveJsonAttribute());
        bind(new PrimitiveJsonNextObject());
        bind(new PrimitiveKill());
        bind(new PrimitiveLambdaP());
        bind(new PrimitiveLength());
        bind(new PrimitiveListP());
        bind(new PrimitiveListRef());
        bind(new PrimitiveLoad(modules));
        bind(new PrimitiveLoadModule(modules));
        bind(new PrimitiveLocalTzOffset());
        bind(new PrimitiveLog());
        bind(new PrimitiveMD5Hash());
        bind(new PrimitiveMacroexpand(modules));
        bind(new PrimitiveMakeBytevector());
        bind(new PrimitiveMakeConditionVariable());
        bind(new PrimitiveMakeDict());
        bind(new PrimitiveMakeDirectory());
        bind(new PrimitiveMakeErrorObject());
        bind(new PrimitiveMakeHashTable());
        bind(new PrimitiveMakeHttpRequest());
        bind(new PrimitiveMakeHttpResponse());
        bind(new PrimitiveMakeInstruction());
        bind(new PrimitiveMakeMutex());
        bind(new PrimitiveMakeParameterCore());
        bind(new PrimitiveMakePolar());
        bind(new PrimitiveMakeRecord());
        bind(new PrimitiveMakeRectangular());
        bind(new PrimitiveMakeString());
        bind(new PrimitiveMakeSymlink());
        bind(new PrimitiveMakeThread(modules));
        bind(new PrimitiveMakeVector());
        bind(new PrimitiveMember());
        bind(new PrimitiveMemq());
        bind(new PrimitiveMemv());
        bind(new PrimitiveModuleBind(modules));
        bind(new PrimitiveModuleBindings(modules));
        bind(new PrimitiveModuleDefinedBindings(modules));
        bind(new PrimitiveModuleExportBindings(modules));
        bind(new PrimitiveModuleExports(modules));
        bind(new PrimitiveModuleImportBindings(modules));
        bind(new PrimitiveModuleRef(modules));
        bind(new PrimitiveModulo());
        bind(new PrimitiveMonotonicNanosecond());
        bind(new PrimitiveMoveDirectory());
        bind(new PrimitiveMoveFile());
        bind(new PrimitiveMul());
        bind(new PrimitiveMutexLockB());
        bind(new PrimitiveMutexName());
        bind(new PrimitiveMutexP());
        bind(new PrimitiveMutexSpecific());
        bind(new PrimitiveMutexSpecificSetB());
        bind(new PrimitiveMutexState());
        bind(new PrimitiveMutexUnlockB());
        bind(new PrimitiveNewline(modules));
        bind(new PrimitiveNormalizedPath());
        bind(new PrimitiveNot());
        bind(new PrimitiveNullP());
        bind(new PrimitiveNumberP());
        bind(new PrimitiveNumberToString());
        bind(new PrimitiveNumequal());
        bind(new PrimitiveNumgreater());
        bind(new PrimitiveNumgreaterequal());
        bind(new PrimitiveNumless());
        bind(new PrimitiveNumlessequal());
        bind(new PrimitiveOpenBinaryInputFile());
        bind(new PrimitiveOpenBinaryOutputFile());
        bind(new PrimitiveOpenInputBytevector());
        bind(new PrimitiveOpenInputFile());
        bind(new PrimitiveOpenInputString());
        bind(new PrimitiveOpenInputZipFile());
        bind(new PrimitiveOpenJsonFile());
        bind(new PrimitiveOpenJsonString());
        bind(new PrimitiveOpenOutputBytevector());
        bind(new PrimitiveOpenOutputFile());
        bind(new PrimitiveOpenOutputString());
        bind(new PrimitiveOpenOutputZipBytevector());
        bind(new PrimitiveOpenOutputZipFile());
        bind(new PrimitiveOpenRandomAccessFile());
        bind(new PrimitiveOpenXmlBytevector());
        bind(new PrimitiveOpenXmlFile());
        bind(new PrimitiveOpenXmlString());
        bind(new PrimitiveOutputPortOpenP());
        bind(new PrimitiveOutputPortP());
        bind(new PrimitivePBKDF2SHA256());
        bind(new PrimitivePairP());
        bind(new PrimitivePairSource());
        bind(new PrimitivePathExistsP());
        bind(new PrimitiveParentPid());
        bind(new PrimitivePeekChar(modules));
        bind(new PrimitivePeekU8());
        bind(new PrimitivePgParseDatarow());
        bind(new PrimitivePgQuoteLiteral());
        bind(new PrimitivePgrep());
        bind(new PrimitivePkill());
        bind(new PrimitivePortPosition(modules));
        bind(new PrimitivePrimitive(this));
        bind(new PrimitivePrimitiveP());
        bind(new PrimitiveProcedureDoc(modules));
        bind(new PrimitiveProcessAliveQ());
        bind(new PrimitiveProcessKill());
        bind(new PrimitiveProcessKillOnExit());
        bind(new PrimitiveProcessNanosecond());
        bind(new PrimitiveProcessPid());
        bind(new PrimitiveProcessWait());
        bind(new PrimitivePs());
        bind(new PrimitivePsInfo());
        bind(new PrimitiveQuotient());
        bind(new PrimitiveRaiseFatal());
        bind(new PrimitiveRandomAccessFileFlush());
        bind(new PrimitiveRandomAccessFileP());
        bind(new PrimitiveRandomAccessFileRead());
        bind(new PrimitiveRandomAccessFileSize());
        bind(new PrimitiveRandomAccessFileTruncateB());
        bind(new PrimitiveRandomAccessFileWriteB());
        bind(new PrimitiveRandomBytes());
        bind(new PrimitiveRationalDenominator());
        bind(new PrimitiveRationalNumerator());
        bind(new PrimitiveRead(modules));
        bind(new PrimitiveReadBytevector());
        bind(new PrimitiveReadBytevectorB());
        bind(new PrimitiveReadChar(modules));
        bind(new PrimitiveReadChars(modules));
        bind(new PrimitiveReadErrorP());
        bind(new PrimitiveReadLine(modules));
        bind(new PrimitiveReadSymlink());
        bind(new PrimitiveReadU8());
        bind(new PrimitiveRealP());
        bind(new PrimitiveRecordP());
        bind(new PrimitiveRecordRef());
        bind(new PrimitiveRecordSetB());
        bind(new PrimitiveRemainder());
        bind(new PrimitiveResetModules(modules));
        bind(new PrimitiveRound());
        bind(new PrimitiveRsaDecrypt());
        bind(new PrimitiveRsaEncrypt());
        bind(new PrimitiveRsaGenerateKeypair());
        bind(new PrimitiveRunProgram());
        bind(new PrimitiveRunProgramCapture());
        bind(new PrimitiveSHA1Hash());
        bind(new PrimitiveSHA256Hash());
        bind(new PrimitiveSecond());
        bind(new PrimitiveServerInstallShutdownHook());
        bind(new PrimitiveServerStop());
        bind(new PrimitiveServerWait());
        bind(new PrimitiveSetCarB());
        bind(new PrimitiveSetCdrB());
        bind(new PrimitiveSetCodeB());
        bind(new PrimitiveSetCurrentDirectory());
        bind(new PrimitiveSetCurrentModule(modules));
        bind(new PrimitiveSetFileModificationTime());
        bind(new PrimitiveSin());
        bind(new PrimitiveSocketBinaryInputPort());
        bind(new PrimitiveSocketBinaryOutputPort());
        bind(new PrimitiveSocketClose());
        bind(new PrimitiveSocketInputPort());
        bind(new PrimitiveSocketOutputPort());
        bind(new PrimitiveSocketP());
        bind(new PrimitiveSocketReadLine());
        bind(new PrimitiveSocketStarttls());
        bind(new PrimitiveSpecialFolderApplicationData());
        bind(new PrimitiveSpecialFolderDocuments());
        bind(new PrimitiveSpecialFolderTemp());
        bind(new PrimitiveSpecialFolderUserHome());
        bind(new PrimitiveSqrt());
        bind(new PrimitiveStartProgram());
        bind(new PrimitiveString());
        bind(new PrimitiveStringAppend());
        bind(new PrimitiveStringContains());
        bind(new PrimitiveStringCopy());
        bind(new PrimitiveStringDowncase());
        bind(new PrimitiveStringEqP());
        bind(new PrimitiveStringFoldcase());
        bind(new PrimitiveStringGreaterEqP());
        bind(new PrimitiveStringGreaterP());
        bind(new PrimitiveStringJoin());
        bind(new PrimitiveStringLength());
        bind(new PrimitiveStringLessEqP());
        bind(new PrimitiveStringLessP());
        bind(new PrimitiveStringMatches());
        bind(new PrimitiveStringP());
        bind(new PrimitiveStringPrefixP());
        bind(new PrimitiveStringRef());
        bind(new PrimitiveStringReplace());
        bind(new PrimitiveStringReplaceRegex());
        bind(new PrimitiveStringSetB());
        bind(new PrimitiveStringSplit());
        bind(new PrimitiveStringSplitVector());
        bind(new PrimitiveStringSuffixP());
        bind(new PrimitiveStringToDateDays());
        bind(new PrimitiveStringToDateSeconds());
        bind(new PrimitiveStringToNumber());
        bind(new PrimitiveJsonSimpleToString());
        bind(new PrimitiveJsonSimpleToPrettyString());
        bind(new PrimitiveJsonSimpleParse());
        bind(new PrimitiveStringToSymbol());
        bind(new PrimitiveStringToUtf8());
        bind(new PrimitiveStringUpcase());
        bind(new PrimitiveSub());
        bind(new PrimitiveSubstring());
        bind(new PrimitiveSymbolP());
        bind(new PrimitiveSymbolStartsWith());
        bind(new PrimitiveSymbolToString());
        bind(new PrimitiveSyntaxToDatum());
        bind(new PrimitiveSysMachineName());
        bind(new PrimitiveSysNumCPUCores());
        bind(new PrimitiveSysOsVersion());
        bind(new PrimitiveSysPlatform());
        bind(new PrimitiveSysScmTechnology());
        bind(new PrimitiveSysScmVersion());
        bind(new PrimitiveSysUserName());
        bind(new PrimitiveTan());
        bind(new PrimitiveTcpAccept());
        bind(new PrimitiveTcpConnect());
        bind(new PrimitiveTcpHttpServe(modules));
        bind(new PrimitiveTcpListen());
        bind(new PrimitiveTcpListenerP());
        bind(new PrimitiveTdsConnect());
        bind(new PrimitiveTlsConnect());
        bind(new PrimitiveTerminalByteReadyP());
        bind(new PrimitiveTerminalEnableAnsiB());
        bind(new PrimitiveTerminalP());
        bind(new PrimitiveTerminalRawB());
        bind(new PrimitiveTerminalReadByte());
        bind(new PrimitiveTerminalSize());
        bind(new PrimitiveTerminatedThreadExceptionP());
        bind(new PrimitiveTextualPortP());
        bind(new PrimitiveThreadJoinB());
        bind(new PrimitiveThreadName());
        bind(new PrimitiveThreadNanosecond());
        bind(new PrimitiveThreadP());
        bind(new PrimitiveThreadSleepB());
        bind(new PrimitiveThreadSpecific());
        bind(new PrimitiveThreadSpecificSetB());
        bind(new PrimitiveThreadStartB());
        bind(new PrimitiveThreadTerminateB());
        bind(new PrimitiveThreadYieldB());
        bind(new PrimitiveTimestamp());
        bind(new PrimitiveTimestampToString());
        bind(new PrimitiveTruncate());
        bind(new PrimitiveUncaughtExceptionP());
        bind(new PrimitiveUncaughtExceptionReason());
        bind(new PrimitiveUtf8ToString());
        bind(new PrimitiveValues());
        bind(new PrimitiveVector());
        bind(new PrimitiveVectorLength());
        bind(new PrimitiveVectorP());
        bind(new PrimitiveVectorRef());
        bind(new PrimitiveVectorSetB());
        bind(new PrimitiveWhich());
        bind(new PrimitiveWindersGet());
        bind(new PrimitiveWindersSet());
        bind(new PrimitiveWrite(modules));
        bind(new PrimitiveWriteBytevector());
        bind(new PrimitiveWriteChar(modules));
        bind(new PrimitiveWriteShared(modules));
        bind(new PrimitiveWriteSimple(modules));
        bind(new PrimitiveWriteString(modules));
        bind(new PrimitiveWriteU8());
        bind(new PrimitiveWsAccept());
        bind(new PrimitiveWsClose());
        bind(new PrimitiveWsConnect());
        bind(new PrimitiveWsP());
        bind(new PrimitiveWsReceive());
        bind(new PrimitiveWsSend());
        bind(new PrimitiveXmlAttribute());
        bind(new PrimitiveXmlName());
        bind(new PrimitiveXmlNodeType());
        bind(new PrimitiveXmlRead());
        bind(new PrimitiveXmlReadTo());
        bind(new PrimitiveXmlValue());
        bind(new PrimitiveXorKey());
        bind(new PrimitiveZipAddBinaryEntry());
        bind(new PrimitiveZipAddStoredEntry());
        bind(new PrimitiveZipAddTextEntry());
        bind(new PrimitiveZipEntryNames());
        bind(new PrimitiveZipReadEntryBytevector());
        bind(new PrimitiveZlibCompress());
        bind(new PrimitiveZlibDecompress());
    }

    public Object getPrimitive(SourcePos pos, String name) {
        Object value = primitives.get(name);
        if (value == null) {
            throw new SchemeError(pos, "Primitives: " + name + " is not a primitive");
        }
        return value;
    }

    public Object getPrimitive(String name) {
        Object value = primitives.get(name);
        if (value == null) {
            throw new SchemeError("Primitives: " + name + " is not a primitive");
        }
        return value;
    }

    public boolean hasPrimitive(String name) {
        return primitives.containsKey(name);
    }

    public List<String> allPrimitives() {
        return new ArrayList<>(primitives.keySet());
    }

    private void bind(Primitive primitive) {
        bind(primitive.name(), primitive);
    }

    private void bind(String name, Object value) {
        if (primitives.containsKey(name)) {
            throw new SchemeError("Primitives: duplicate " + name);
        }
        primitives.put(name, value);
    }

    private Object getCallCC() {
        List<Instruction> instructions = new ArrayList<>();
        instructions.add(new Instruction(Opcode.ARGS, 1));
        instructions.add(new Instruction(Opcode.CC));
        instructions.add(new Instruction(Opcode.LVAR, 0, 0));
        instructions.add(new Instruction(Opcode.CALLJ, 1));
        Lambda callcc = new Lambda(Value.NIL, instructions);
        callcc.name = "call-with-current-continuation";
        callcc.doc = "Syntax: (call-with-current-continuation proc)\nLibrary: (scheme base)\nDescription: Calls proc with the current continuation as its argument.\n  The continuation is a procedure that, when called with a value, returns\n  that value to the point where call/cc was invoked.\nExample:\n  (call-with-current-continuation (lambda (k) (k 42))) => 42";
        return callcc;
    }

    private Object getApply() {
        List<Instruction> instructions = new ArrayList<>();
        instructions.add(new Instruction(Opcode.ARGSDOT, 1));
        instructions.add(new Instruction(Opcode.FLATTEN_APPLY, 0, 1));
        instructions.add(new Instruction(Opcode.LVAR, 0, 0));
        instructions.add(new Instruction(Opcode.CALLJ, -1));
        Lambda apply = new Lambda(Value.NIL, instructions);
        apply.name = "apply";
        apply.doc = "Syntax: (apply proc arg1 ... args)\nLibrary: (scheme base)\nDescription: Calls proc with the given arguments. The last argument must\n  be a list, whose elements are appended to the preceding arguments.\nExample:\n  (apply + 1 2 '(3 4)) => 10";
        return apply;
    }

    private Object getCallWithValues() {
        List<Instruction> instructions = new ArrayList<>();
        instructions.add(new Instruction(Opcode.ARGS, 2));
        instructions.add(new Instruction(Opcode.SAVE, 4));
        instructions.add(new Instruction(Opcode.LVAR, 0, 0));
        instructions.add(new Instruction(Opcode.CALLJ, 0));
        instructions.add(new Instruction(Opcode.FLATTEN_MULTVALS, 0, 1));
        instructions.add(new Instruction(Opcode.LVAR, 0, 1));
        instructions.add(new Instruction(Opcode.CALLJ, -1));
        Lambda apply = new Lambda(Value.NIL, instructions);
        apply.name = "call-with-values";
        apply.doc = "Syntax: (call-with-values producer consumer)\nLibrary: (scheme base)\nDescription: Calls producer with no arguments. The producer must return\n  zero or more values. The consumer is then called with those values as\n  arguments. Returns the result of consumer.\nExample:\n  (call-with-values (lambda () (values 1 2)) +) => 3";
        return apply;
    }
}
